// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHzNnICZSXmTGSTXG3ee3Yy4nYBAWSYEU',
    appId: '1:1011838485758:web:f0bd34c58b645ee98f91af',
    messagingSenderId: '1011838485758',
    projectId: 'habitly-auth-test',
    authDomain: 'habitly-auth-test.firebaseapp.com',
    storageBucket: 'habitly-auth-test.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQYs8iHGczaKjl9Pgc0Xw0Nm7vYiiFMkM',
    appId: '1:1011838485758:android:216c1b21fa8ec8ea8f91af',
    messagingSenderId: '1011838485758',
    projectId: 'habitly-auth-test',
    storageBucket: 'habitly-auth-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ-69_JcoDEMiR6g1JNI-oeYKT-Lbj3JI',
    appId: '1:1011838485758:ios:cf41fb35121c29508f91af',
    messagingSenderId: '1011838485758',
    projectId: 'habitly-auth-test',
    storageBucket: 'habitly-auth-test.firebasestorage.app',
    iosBundleId: 'dev.artan.habitly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ-69_JcoDEMiR6g1JNI-oeYKT-Lbj3JI',
    appId: '1:1011838485758:ios:8a9da2652aeb720c8f91af',
    messagingSenderId: '1011838485758',
    projectId: 'habitly-auth-test',
    storageBucket: 'habitly-auth-test.firebasestorage.app',
    iosBundleId: 'com.artan.habitly',
  );
}
